site_name: CMSE890-602 Project

theme: 
  name: material
  color_mode: dark
  user_color_mode_toggle: true
  palette:
    scheme: slate
    primary: green

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
nav:
  - Home: index.md
  - Muon Selection: 
    - Selection Class Overview: muonselection.md
    - Class Initialization: muon_init.md
    - Cluster: cluster.md
    - Test merge condition: merge_cluster.md
    - PCA Fit: pcas.md
    - Length Calculation: length.md
    - Through-going Check: close_to_two_faces.md
    - Clean Track: clean_noise_hits.md
    - Average Distance: average_distance.md
    - Test if muon: select_muon_track.md
    - Separate io groups: tpc_separation.md
    - Create segments: segments.md
    - Grab segment info: grab_segment_info.md
    - Run Selection: run.md
  - Electron Lifetime:
    - Convolution: convolution.md
    - Lifetime Function: lifetimefunc.md
    - Landau Gaussian Convolution Function: langaufunc.md
    - Chi Squared: chisquared.md
    - Landau Gaussian Convolution fit: langaufit.md
    - Lifetime Extraction: lifetimefit.md
  - About: about.md