site_name: CMSE890-602 Project

theme: 
  name: material
  color_mode: dark
  user_color_mode_toggle: true
  palette:
    scheme: slate
    primary: green

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
nav:
  - Home: index.md
  - Install and Run: installation.md
  - How-To-Guides: parsing.md
  - Muon Selection: 
    - Selection Class Overview: muonselection.md
    - Class Initialization: muon_init.md
    - Cluster: cluster.md
    - Test merge condition: merge_cluster.md
    - PCA Fit: pcas.md
    - Length Calculation: length.md
    - Through-going Check: close_to_two_faces.md
    - Clean Track: clean_noise_hits.md
    - Average Distance: average_distance.md
    - Test if muon: select_muon_track.md
    - Separate io groups: tpc_separation.md
    - Create segments: segments.md
    - Grab segment info: grab_segment_info.md
    - Run Selection: run.md
  - Electron Lifetime:
    - Convolution: convolution.md
    - Lifetime Function: lifetimefunc.md
    - Landau Gaussian Convolution Function: langaufunc.md
    - Chi Squared: chisquared.md
    - Landau Gaussian Convolution fit: langaufit.md
    - Lifetime Extraction: lifetimefit.md
  - Purity:
    - Purity Overview: purity.md
    - Purity Initialization: purity_init.md
    - Grab Backtrack Information: grab_bt.md
    - Get Trajectory Makeup: get_traj_makeup.md
    - Get PDG key: get_max_pdg.md
    - Measure Purity: purity_measurement.md
    - Random Colors: generate_colors.md
    - Plot Purity: make_plot.md
    - Produce Purity and Plot: purity_and_plot.md
  - Efficiency:
    - Check Point Position: point_outside.md
    - Check Intersection: intersection.md
    - Amount Of True Muons: eff.md
  - References: References.md
