name: selection_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.11.14
  - pip=25.3
  - snakemake=9.14.1
  - numpy==1.25.2
  - pandas=2.3.3
  - matplotlib=3.10.7
  - scipy=1.16.3
  - scikit-learn=1.7.2
  - seaborn=0.13.2
